### PR TITLE
Migrate to Swift 4.2

### PR DESCRIPTION
**Pull request by rmuhamedgaliev**

### CODE REVIEW

**Comment by rmuhamedgaliev** [comment]
Any news?

**Comment by falkobuttler** [comment]
When will this be merged? It's the only Swift framework I use that has not been migrated.

**Comment by pvroosendaal** [comment]
Any news on this? It's unbelievable this framework has not had an update for so long.

**Comment by pvroosendaal** [comment]
@rmuhamedgaliev Why did you close this PR?

**Comment by rmuhamedgaliev** [comment]
I'm tired of waiting and receiving notifications about this pull request. Anyway, no one needs it apparently.

**Comment by pvroosendaal** [comment]
Ok. We're thinking of just consuming the REST API in stead of using this SDK since there's no updates on it.

**Pull request closed without merging**
